### ISSUE TITLE
Fails in Safari

### ISSUE THREAD

**Issue by ayazhafiz** [g1eb/cli-plugin#1]
The plugin doesn't work in Safari. The input field is not editable, but does recognize when the enter key is pressed.

**Comment by g1eb** [comment]
Hi, nice find! :)

I want to merge this fix, but before I do I have a quick question, why did you double the focus on the input element?

on line 157 in src/cli-plugin.js: ```cliPlugin.inputElement.focus();```

Seems a bit out of place (maybe left over workaround?) but I would understand if it has a purpose. 

Thanks again!

**Comment by g1eb** [comment]
I'm going to check that focus issue on Safari, seems like it still won't focus on input element after you select output text.

**Comment by g1eb** [comment]
FYI: I wrapped the ```focus()``` in a timeout callback to fix this.

Thanks again for helping out! 😃 

v0.0.7

**Comment by ayazhafiz** [comment]
Yep, it was a overlooked nuance. Sorry about that!
